development:
  address: "mailtrap.io"
  port: "2525"
  user_name: "hotchalk-canvas-dev-aaaf289df2ffbdca"
  password: "b1733448d6491957"
  authentication: "cram_md5"
  domain: "dev.hotchalkember.com"
  outgoing_address: "ember@dev.hotchalkember.com"
  default_name: "HotChalk Ember Dev"

# or to use sendmail --
#
# development:
#   delivery_method: "sendmail"

test:
  delivery_method: "test"

production:
  address: "mailtrap.io"
  port: "2525"
  user_name: "hotchalk-canvas-dev-aaaf289df2ffbdca"
  password: "b1733448d6491957"
  authentication: "cram_md5"
  domain: "dev.hotchalkember.com"
  outgoing_address: "ember@dev.hotchalkember.com"
  default_name: "HotChalk Ember Dev"

# If receiving mail from multiple inboxes (see incoming_mail.yml.example),
# you'll want to include those addresses in a reply_to_addresses array so
# Canvas will select the Reply-To field of outgoing messages from all of the
# incoming mailboxes.

multiple_inboxes:
  address: "smtp.example.com"
  port: "25"
  user_name: "user"
  password: "password"
  authentication: "plain" # plain, login, or cram_md5
  domain: "example.com"
  outgoing_address: "canvas@example.com"
  default_name: "HotChalk Ember"
  reply_to_addresses:
  - "canvas1@example.com"
  - "canvas2@example.com"
  - "canvas3@example.com"
  - "canvas4@example.com"
